name: Metrics - Isocalendar
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/isocalendar-fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Shuh3n
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
